name: Publish Docker image
description: Publishes a Docker image to a private registry

inputs:
  manifest-file:
    description: Path of the manifest file
    required: true
    default: manifest.json
  registry-username:
    description: Registry username
    required: true
  registry-password:
    description: Registry password
    required: true
  docker-registry-url:
    description: Docker registry URL
    required: true
    default: docker.registry.master-software.de
  build-args:
    description: Additional build arguments
    required: false
    default: ""

outputs:
  image-tag:
    description: Image tag
    value: ${{ steps.set-tag.outputs.image-tag }}

runs:
  using: composite
  steps:
    - name: Login to image registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker-registry-url }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - id: set-tag
      name: Set image tag
      shell: bash
      run: |
        IMAGE_TAG=$(cat ${{ inputs.manifest-file }} | jq -r '"${{ inputs.docker-registry-url }}/\(.name | capture("^(?<scope>@[^/]+)?/?(?<name>.+)$").name):\(.version)"')
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.set-tag.outputs.image-tag }}
        build-args: ${{ inputs.build-args }}
